export const  FETCH_REQUEST = "FETCH_REQUEST";
export const  FETCH_SUCCESS = "FETCH_SUCCESS";
export const  FETCH_ERROR = "FETCH_ERROR";
export const UPDATE_ADDRESS_INPUT = "UPDATE_ADDRESS_INPUT";
export const  FORCAST_FETCH_REQUEST = "FORCAST_FETCH_REQUEST";
export const  FORCAST_FETCH_SUCCESS = "FORCAST_FETCH_SUCCESS";
export const  FORCAST_FETCH_ERROR = "FORCAST_FETCH_ERROR";
